# Copyright 2022 Nordcloud Oy or its affiliates. All Rights Reserved.

steps:
- task: KubernetesManifest@0
  displayName: Install capact CRD
  inputs:
    kubernetesServiceConnection: sm-dev
    namespace: capact-system
    manifests: |
      deploy/kubernetes/crds/core.capact.io_actions.yaml

- task: HelmDeploy@0
  displayName: Install neo4j helm chart
  inputs:
    connectionType: GKE Connection
    kubernetesServiceEndpoint: sm-dev
    namespace: capact-system
    command: upgrade
    chartType: filepath
    chartPath: deploy/kubernetes/charts/neo4j
    releaseName: neo4j

- script: |
    helm list -A
    kubectl get ns

- task: HelmDeploy@0
  displayName: Install ingress-nginx helm chart
  inputs:
    connectionType: GKE Connection
    kubernetesServiceEndpoint: sm-dev
    namespace: capact-system
    command: upgrade
    chartType: filepath
    chartPath: deploy/kubernetes/charts/ingress-controller
    releaseName: ingress-nginx

- task: HelmDeploy@0
  displayName: Install argo helm chart
  inputs:
    connectionType: GKE Connection
    kubernetesServiceEndpoint: sm-dev
    namespace: capact-system
    command: upgrade
    chartType: filepath
    chartPath: deploy/kubernetes/charts/argo
    releaseName: argo
    arguments: --reuse-values
  
- task: HelmDeploy@0
  displayName: Install cert-manager helm chart
  inputs:
    connectionType: GKE Connection
    kubernetesServiceEndpoint: sm-dev
    namespace: capact-system
    command: upgrade
    chartType: filepath
    chartPath: deploy/kubernetes/charts/cert-manager
    releaseName: cert-manager

- task: HelmDeploy@0
  displayName: Install kubed helm chart
  inputs:
    connectionType: GKE Connection
    kubernetesServiceEndpoint: sm-dev
    namespace: capact-system
    command: upgrade
    chartType: filepath
    chartPath: deploy/kubernetes/charts/kubed
    releaseName: kubed

- task: HelmDeploy@0
  displayName: Install capact helm chart
  inputs:
    connectionType: GKE Connection
    kubernetesServiceEndpoint: sm-dev
    namespace: capact-system
    command: upgrade
    chartType: filepath
    chartPath: deploy/kubernetes/charts/capact
    releaseName: capact

# - task: HelmDeploy@0
#   displayName: Deploy monitoring helm chart
#   inputs:
#     connectionType: GKE Connection
#     kubernetesServiceEndpoint: sm-dev
#     namespace: capact-system
#     command: upgrade
#     chartType: filepath
#     chartPath: deploy/kubernetes/charts/monitoring
#     releaseName: monitoring
