steps:
- task: KubernetesManifest@0
  displayName: Install capact CRD
  inputs:
    kubernetesServiceConnection: sm-dev
    namespace: capact-system
    manifests: |
      deploy/kubernetes/crds/core.capact.io_actions.yaml

- task: DownloadSecureFile@1
  name: serviceAccount
  displayName: 'Download service account key file'
  inputs:
    secureFile: 'sm-cluster-dev-73af177dbab6.json'

- script: |
    echo "Login GKE cluster"
    gcloud auth activate-service-account --key-file $(serviceAccount.secureFilePath)
    gcloud container clusters get-credentials sm-dev --zone europe-west1-b --project sm-cluster-dev

- task: KubectlInstaller@0
  displayName: Kubectl installer
  inputs: 
    kubectlVersion: latest

- task: HelmInstaller@1
  displayName: Helm installer
  inputs: 
    helmVersionToInstall: latest

- task: Bash@3
  displayName: Install helm releases
  inputs:
    targetType: FilePath
    filePath: deploy/kubernetes/scripts/deploy_capact_gke.sh
