# Default values for Capact.
global:
  containerRegistry:
    path: gcr.io/sm-cluster-dev
    # Overrides the image tag for all Capact components. Default is the sub-chart appVersion.
    overrideTag: "latest"
  # domainName: "stage.cluster.capact.dev"
  domainName: "34.78.51.195.nip.io"

  database:
    endpoint: bolt://neo4j-neo4j:7687
    username: neo4j
    password: okon

  gateway:
    auth:
      username: graphql
      password: t0p_s3cr3t

dashboard:
  image:
    # Overrides the image path provided in globals (`global.containerRegistry.path`).
    path: gcr.io/sm-cluster-dev
    # Overrides the image tag provided in globals (`global.containerRegistry.overrideTag`).
    tag: "latest"

integrationTest:
  image:
    name: e2e-test
    pullPolicy: Always

testStorageBackend:
  enabled: false

postInstallTypeInstanceJob:
  image:
    name: populator
    pullPolicy: Always
  args: ["/app register capact-installation"]

notes:
  printInsecure: false
